apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-deployment
  labels:
    app: api-app
spec:
  replicas: 2 # Две реплики для отказоустойчивости
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app-container
          image: books-app:latest # Имя собранного вами Docker-образа
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Направляем Spring Boot на нашу Кафку внутри Kubernetes кластера
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/otus"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  type: NodePort # Открывает порт наружу на вашем компьютере
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080