spring:
  main:
    allow-circular-references: true

  shell:
    interactive:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
