spring:
  main:
    allow-circular-references: true

  shell:
    interactive:
      enabled: true
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true
