spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otus
    # для запуска в контейнере
#    url: jdbc:postgresql://host.docker.internal:5432/otus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:schema/db-master-changelog.xml
    enabled: true


  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
